### ISSUE TITLE
1.3 sample_points

### ISSUE THREAD

**Issue by nc1m** [automl-classroom/iML-ws21-ex04#4]
Hi,

for task 1.3 I used the ConfigSpace library to sample points like this:
```
...
random.seed(seed)
confSpace.seed(seed)  # doesn't work with or without it
for config in confSpace.sample_configuration(num_points):
    X.append([config[x0Name], config[x1Name]])
X = np.array(X)
y = model.predict(X)
```

But the tests looks for specific y values and fails:
```
assert y[0] == 2
assert y[-4] == 0
assert y[-5] == 1
```

Do I have the wrong approach?

**Comment by renesass** [comment]
That's actually a good approach. However, I solved the task using `random.uniform` - that's why your tests fail. Sorry, I should have further specified.

**Comment by rhotertj** [comment]
The sentence "having a detailed look into the API will save you a lot of time" was kind of misleading in that case :)

**Comment by renesass** [comment]
Well, it was meant for the hyperparameter_dict function and the float hyperparameters. Anyway, thanks for the feedback. I will update it shortly. :)

**Comment by nc1m** [comment]
> That's actually a good approach. However, I solved the task using `random.uniform` - that's why your tests fail. Sorry, I should have further specified.

Thanks, now it works.
